### ISSUE TITLE
Randomness result after create some keyframes

### ISSUE THREAD

**Issue by junehui** [jzubizarreta/dsm#10]
I got some randomnessly result after trackFrame, the Least Squares Problem report differently between different tries, somewhere unstable:

the same frame:

sample 1:
Least Squares Problem report
----------------------------
        Residuals : 119952, 119952, 119952
       Parameters : 2753, 2753, 2753
       Iterations : 9 (9), 9 (9), 5 (5)
     Initial RMSE : 3.54142, 3.24045, 3.14537
       Final RMSE : 3.21747, 2.77827, 2.83725
             Time : 182.291, 189.567, 111.58 [ms]
      Termination : User success, User success, User success

sample2:
 Least Squares Problem report
 ----------------------------
         Residuals : 34376, 34376, 34376
        Parameters : 2236, 2236, 2236
        Iterations : 7 (7), 6 (6), 5 (5)
      Initial RMSE : 2.90104, 2.29377, 2.80954
        Final RMSE : 2.37894, 1.98264, 2.64797
              Time : 45.597, 37.316, 28.814 [ms]
       Termination : User success, User success, User success

**Comment by jzubizarreta** [comment]
This is absolutely a normal behaviour. Ceres-solver contains some non-deterministic strategies that DSM cannot control.
