### ISSUE TITLE
3D Visualization not rendered

### ISSUE THREAD

**Issue by laxnpander** [jzubizarreta/dsm#12]
Hey, 

I installed DSM on a freshly setup laptop with Ubuntu 18.04 according to your readme. However, qt5-default seems to be not sufficient. I can start the qt application, but only the images not the 3D is displayed. The installed version from repository for me is 5.9.5. I will try to run it with 5.10 and report back here.

Edit: Also an update to 5.10.1 did not resolve the issue.

**Comment by jzubizarreta** [comment]
Hi @laxnpander, I need more information to figure out what is happening please. Try to debug the rending code of the UI.

**Comment by jzubizarreta** [comment]
I close this issue. Reopen it if required.

**Comment by Sachet12345** [comment]
Hi @laxnpander, did you manage to solve this issue?
