### ISSUE TITLE
Saving trajectory, map, and evaluation

### ISSUE THREAD

**Issue by NikolausDemmel** [jzubizarreta/dsm#13]
We would like to reproduce your nice results from the paper, but some details about the evaluation are unclear. Maybe you can help clarify. Thanks in advance!

1. It seems currently saving the trajectory to some text file (e.g. TUM RGBD format) for evaluation is not implemented in the github version, or did I miss it? I only found the save button that generates the a ply file for the point cloud. I guess it wouldn't be hard to add, but I was just woundering how you generated the results for evaluation.

2. When reporting ATE, do you compute it for every keyframe, or also non keyframes? Which pose do you use for a keyframe? The final one at the end of the program after all optimizations?

3. For the ATE as I know it people report RMSE translational error after Sim3 alignment. But for the map error, it is not clear to me. You write "The PSE is estimated measuring the distance of the reconstructed model to the ground-truth surface after the trajectory alignment. ". How exactly is PSE defined (sum, mean, rmse, median....) and over which points (is there any kind of filtering of outliers etc)? If its a standard metric, do you maybe have a reference that explains it more? For Euroc, the groundtruth AFAIK is only given as a point cloud of a 3D laser scan. The alignment part should be clear (same alignment as for ATE, based on the keyframe poses), but how exactly do you compute a surface from the gt point cloud. Do you maybe have tools or scripts to share to compute the map error? That would be super helpful.

**Comment by jzubizarreta** [comment]
Hi Nikolaus,

Yes of course! I will try to clarify them the best I can.

1. Yes your are right. The code for evaluating the result have not been uploaded to github. During evaluation I used to export the trajectory using the TUM RGBD format, if I am not wrong. You could implement yourself the file writer and use one of the scripts available in the community to evaluate the ATE. Anyway, I will try to recovere those code files and include them in this repo (but maybe not soon).

2. Yes we evaluate the ATE on the keyframes as explained in the paper. For evaluating the final trajectory error, we use the pose at the end of the program.

3. For PSE we do not use any filtering of outliers. We use all the points in the reconstruction. The given measurements are accumulated plots, so we do not use any specific measurement. We just plot the error (distance) of each of the points in accumulated form (Fig. 10) using all the runs (10 for each sequence in our case). This gives a more detailed view of how to distribution of errors is. Yes, we use the same alignement as for the keyframes and then compute the distance to the closest surface using the libicp from http://www.cvlibs.net/software/libicp/. Even if we do not use the ICP algorithm (as we only use the alignment from the keyrames), it contains very useful functions to obtain the closest surface between a reconstructed point and the ground-truth pointcloud.

**Comment by NikolausDemmel** [comment]
Thanks for your quick and very helpful response!

> Yes your are right. The code for evaluating the result have not been uploaded to github. During evaluation I used to export the trajectory using the TUM RGBD format, if I am not wrong. You could implement yourself the file writer and use one of the scripts available in the community to evaluate the ATE. Anyway, I will try to recovere those code files and include them in this repo (but maybe not soon).

Ok, no problem. This should be easy to add ourselves, as you say.

> Yes we evaluate the ATE on the keyframes as explained in the paper. For evaluating the final trajectory error, we use the pose at the end of the program.

Ok got it. Make sense.

> For PSE we do not use any filtering of outliers. We use all the points in the reconstruction. The given measurements are accumulated plots, so we do not use any specific measurement. We just plot the error (distance) of each of the points in accumulated form (Fig. 10) using all the runs (10 for each sequence in our case). This gives a more detailed view of how to distribution of errors is. Yes, we use the same alignement as for the keyframes and then compute the distance to the closest surface using the libicp from http://www.cvlibs.net/software/libicp/. Even if we do not use the ICP algorithm (as we only use the alignment from the keyrames), it contains very useful functions to obtain the closest surface between a reconstructed point and the ground-truth pointcloud.

Thanks for the pointer to libicp. I haven't used it, but that is very helpful. So I think with that we should be able to reproduce your error computation pretty exactly. Just to recap:

1. Use Sim3 alignment from keyframes (same as for ATE) to align estimated point cloud (at the end of the program) to the ground truth point cloud.
2. For every aligned estimated point, compute the point-to-plane error ("euclidean distance", in meters) using the implementation in libicp.
3. Accumulate all errors to the cumulative histogram plot, showing "percentage of estimated points" on the y axis and "PSE" on the x axis.

Two small questions:
 - In the sentence of the paper, "The results are shown using normalized cumulative error plots, which provide the percentage of runs/points with an error below a certain threshold.", the word "normalized" simply means that you show "percentage" and not "absolute number of points", right? This makes sense when comparing different sequences, or different algorithms that reconstruct different number of points. Or is there some other kind of normalization that I didn't get yet?
 - For every landmark / patch, you generate only 1 point to evaluate (the center pixel)? Or do you generate one point for every pixel in the patch. I think the former make sense here.

Just thinking out loud: One thing this error metric doesn't really take into account is the tradeoff of the algorithm between completely throwing away uncertain points and keeping only the good ones, or keeping as many points as possible (but making sure uncertain/bad points don't affect the estimates), to possibly improve the bad points later. To maximize the PSE map error as above, it would be very beneficial to throw out as many uncertain points as possible, to increase the percentage of good points. This is just a note, I don't really have a good suggestion of what would be a better way to evaluate the map that circumvents this.

**Comment by jzubizarreta** [comment]
Sorry for the late reply.

> Thanks for the pointer to libicp. I haven't used it, but that is very helpful. So I think with that we should be able to reproduce your error computation pretty exactly. Just to recap:
> 
>     1. Use Sim3 alignment from keyframes (same as for ATE) to align estimated point cloud (at the end of the program) to the ground truth point cloud.
> 
>     2. For every aligned estimated point, compute the point-to-plane error ("euclidean distance", in meters) using the implementation in libicp.
> 
>     3. Accumulate all errors to the cumulative histogram plot, showing "percentage of estimated points" on the y axis and "PSE" on the x axis.

Exactly :)

> 
> Two small questions:
> 
>     * In the sentence of the paper, "The results are shown using normalized cumulative error plots, which provide the percentage of runs/points with an error below a certain threshold.", the word "normalized" simply means that you show "percentage" and not "absolute number of points", right? This makes sense when comparing different sequences, or different algorithms that reconstruct different number of points. Or is there some other kind of normalization that I didn't get yet?
> 

It simply means that we show the percentage, instead of use the number of points.

>     * For every landmark / patch, you generate only 1 point to evaluate (the center pixel)? Or do you generate one point for every pixel in the patch. I think the former make sense here.
> 

If I don't remember wrong, we only use the center pixel.

> 
> Just thinking out loud: One thing this error metric doesn't really take into account is the tradeoff of the algorithm between completely throwing away uncertain points and keeping only the good ones, or keeping as many points as possible (but making sure uncertain/bad points don't affect the estimates), to possibly improve the bad points later. To maximize the PSE map error as above, it would be very beneficial to throw out as many uncertain points as possible, to increase the percentage of good points. This is just a note, I don't really have a good suggestion of what would be a better way to evaluate the map that circumvents this.

Yes, I also think that filtering the points would improve the PSE. However, we don't use any filtering in any method to obtain a fair comparison. I don't know either what would be a better option to evaluate the map in that case.

**Comment by NikolausDemmel** [comment]
Thanks for the clarifications! 👍
