### ISSUE TITLE
DSM to process image sequence of UAV

### ISSUE THREAD

**Issue by YRstronger** [jzubizarreta/dsm#14]
Hi, I am trying to use to process some images captured by a camera on a UAV. the problem is almost all the scene is similar plane scene.  Is DSM proper to handle those sequence? Or can you give me some advice about those images

**Comment by jzubizarretagorostidi** [comment]
What do you exactly mean by "similar plane scene"? If you mean that almost all the scene is planar, you should not have any issue. DSM is capable of initializing in planar scenes.

**Comment by jzubizarreta** [comment]
What do you exactly mean by "similar plane scene"? If you mean that almost all the scene is planar, you should not have any issue. DSM is capable of initializing in planar scenes.

**Comment by YRstronger** [comment]
Thanks for your reply!
That is a very unmature problem because at that time I did't run DSM demo. 
I have tested DSM, and the result is very good. Thanks for your excellent work.
