### ISSUE TITLE
Use of OpenGL with macOS

### ISSUE THREAD

**Issue by eu42** [jzubizarreta/dsm#16]
I see that there is a [commit](https://github.com/jzubizarreta/dsm/commit/449c5722b8e26e48c9e7f099b964a23870933040) for macos support but there exists a small problem about it.
 
`#include <GL/glu.h>` should not be present when OS is macOS. It prevents dsm from building successfully. There are 3 such occurrences in `QtVisualizer`.

This [merge request](https://github.com/jzubizarreta/dsm/pull/2) has the working version of the related changes.

I wanted to point this out because seeing conditional include statements for macos makes you think that this code should work if everything is set up correctly.

**Comment by jzubizarreta** [comment]
Thank you @eu42! I will take a look as soon as possible to this part.

**Comment by jzubizarreta** [comment]
This has been integrated into master.
