### ISSUE TITLE
build problem with opengl include

### ISSUE THREAD

**Issue by Yibing-Chen** [jzubizarreta/dsm#17]
It seems related to the issue #16.
I found opengl library was not included in following cpp files:
  QtVisualizer.cpp, MouseInterface.cpp, GLWidget.cpp
which made compile errors.
And I mannual fixed that by add following codes to the above 3 files.

#ifdef __APPLE__
	#include <OpenGL/gl.h>
	#include <OpenGL/glu.h>
#else
	#include <GL/gl.h>
	#include <GL/glu.h>
#endif

**Comment by jzubizarretagorostidi** [comment]
Thank you for the info :)
Could you please make a PR so I can check it?

**Comment by jzubizarreta** [comment]
Thank you for the info :)
Could you please make a  PR so I can check it?

**Comment by jzubizarreta** [comment]
Closing this issue for now, reopen it if required please
