### ISSUE TITLE
Reading Calibration from file: /home/Dsm/dsm/Examples/EurocData/calib0.txt need camera calibration file...

### ISSUE THREAD

**Issue by fantasy520** [jzubizarreta/dsm#22]
I run by this:./EurocExample /home/Dsm/MH_01_easy/mav0/cam0/data /home/Dsm/dsm/Examples/EurocData/Timestamps/MH_01_easy.txt /home/Dsm/dsm/Examples/EurocData/calib0.txt /home/Dsm/dsm/Examples/EurocData/settings.txt
can you tell me what is wrong with that?

**Comment by jzubizarreta** [comment]
Closing this issue as there is not enough information provided. Reopen it if required please.
