### ISSUE TITLE
Export Camera Trajectory

### ISSUE THREAD

**Issue by SimpleMathmatics** [jzubizarreta/dsm#25]
Hi, 
Thank you for this awesome project!
I don't know if I am missing something, but is there a way to export the camera trajectory after the run, or only the pointcloud?
Thank you, 
Julian

**Comment by NikolausDemmel** [comment]
I believe this PR includes a change that adds saving of the trajectory: https://github.com/jzubizarreta/dsm/pull/19

**Comment by SimpleMathmatics** [comment]
Thanks for the fast reply @NikolausDemmel!
perfect, exactly what I was looking for!
