### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [jzubizarreta/dsm#26]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/114840215-29e99400-9e09-11eb-98a6-f5dcebb6c897.png)

thank you  
best regards to you  
William

**Comment by jzubizarreta** [comment]
Hi William, seems you are not linking properly to ceres. Are you using a custom ceres build? Then you need to point the ceres build location to cmake.

**Comment by jzubizarreta** [comment]
Closing this thread. Reopen if required :)
