### ISSUE TITLE
QtVisualizer segmentation fault

### ISSUE THREAD

**Issue by alalagong** [jzubizarreta/dsm#4]
Hi, thanks for your open source, it's really an exciting system!

I have trouble with Qt5, when I compile the code. It show :
```
In file included from /home/gong/Project/C++/dsm/QtVisualizer/src/QtWindow.h:32:0,
                      from /home/gong/Project/C++/dsm/QtVisualizer/src/QtWindow.cpp:24:
/home/gong/Project/C++/dsm/build/QtVisualizer/ui_qtwindow.h: In member function ‘void Ui_QtWindowClass::setupUi(QMainWindow*)’:
/home/gong/Project/C++/dsm/build/QtVisualizer/ui_qtwindow.h:270:25: error: ‘class QCheckBox’ has no member named ‘setTabletTracking’
         cameraCheckBox->setTabletTracking(false);
```
And I can't find func `setTabletTracking() ` in ` /usr/include/x86_64-linux-gnu/qt5/.`

So I try to comment the line` cameraCheckBox->setTabletTracking(false); `in file `build/QtVisualizer/ui_qtwindow.h.`
Then I can compile successfully, but when I run, it occurs segment fault. When I debug, i find that the problem is the func which is `visualizer.run();`.
And I also try to change property  `<property name="tabletTracking">` in `QtVisualizer/src/qtwindow.ui` to other name, it can compile successfully but segment fault.

So may I know how to deal with this problem?

Thank you!

**Comment by venkateshtata** [comment]
Facing same issue !

**Comment by wlt027** [comment]
I got the same problem.I think the reason maybe Qt version.
I use docker to slove this problem.
Running on ubuntu 18.04 
![image](https://user-images.githubusercontent.com/30792512/70371006-5b467b80-1908-11ea-847f-417b343377d6.png)

**Comment by Basavaraj-PN** [comment]
> Facing same issue !

Exactly the same issue. @venkateshtata @wlt027 @jzubizarreta

**Comment by Basavaraj-PN** [comment]
> I got the same problem.I think the reason maybe Qt version.
> I use docker to slove this problem.
> Running on ubuntu 18.04
> ![image](https://user-images.githubusercontent.com/30792512/70371006-5b467b80-1908-11ea-847f-417b343377d6.png)

@wlt027 Can you please share your command sequence to run it.

**Comment by venkateshtata** [comment]
QtVisualizer
Copyright (C) 2019 CEIT (Universidad de Navarra) and Universidad de Zaragoza
Developed by Jon Zubizarreta,
for more information see <https://github.com/jzubizarreta/dsm>.
If you use this code, please cite the respective publications as
listed on the above website.


Qt version 5.5.1
OpenGL Version= 4.6.0 NVIDIA 440.33.01

Reading Calibration from file: mav0/cam0/sensor.yaml
OpenCV Error: Assertion failed (s >= 0) in setSize, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/matrix.cpp, line 310
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/matrix.cpp:310: error: (-215) s >= 0 in function setSize

Aborted (core dumped)
  I AM GETTING THIS ERROR WHEN I TRY TO RUN : `./EurocExample mav0/cam0/data/ mav0/cam0/data.csv mav0/cam0/sensor.yaml`

**Comment by Basavaraj-PN** [comment]
@venkateshtata  I solved it,

**Comment by venkateshtata** [comment]
<img width="800" alt="Screenshot 2019-12-07 at 7 06 51 PM" src="https://user-images.githubusercontent.com/13502680/70375530-c69e4680-1924-11ea-8bd0-7025cc9090ba.png">
I got it working.

**Comment by alalagong** [comment]
That's right!! It's working. My Qt version is 5.5.1, too old. I install Qt5.10(gcc) from here [http://download.qt.io/archive/qt/5.10/5.10.1/](url), then it can work well.

**Comment by CuriousCat-7** [comment]
@alalagong 
The url has been failed.
I solve this problem by install Qt 5.15 from https://www.qt.io/download
and add 
`set(CMAKE_PREFIX_PATH /My_home_path/Qt/5.15.2/gcc_64)`
in file `QtVisualizer/CMakeLists.txt`
