### ISSUE TITLE
class QCheckBox’ has no member named ‘setTabletTracking’ cameraCheckBox->setTabletTracking(false)

### ISSUE THREAD

**Issue by Allenyhf** [jzubizarreta/dsm#8]
I came across a few questions. I have installed QT5 and other dependences, but when I run command 'make -j3',it throws errors as following: ‘ **ui_qtwindow.h:270:25: error: ‘class QCheckBox’ has no member named ‘setTabletTracking’ cameraCheckBox->setTabletTracking(false);**’

**Comment by jzubizarreta** [comment]
That error is because the Qt version. You need a higher version of Qt.
I recommend using ubuntu 18.04 or compile Qt on your own.
